# ---------------------------------------------------------
# KITTY CONFIGURATION - CLEAN & OPTIMIZED
# ---------------------------------------------------------

# -- Colores -- #
include colors/colors.conf

# -- Fuentes -- #
font_size        9.0
disable_ligatures cursor
force_ltr        no

# -- Cursor -- #
cursor_shape                    block
cursor_blink_interval           0
cursor_trail                    3
cursor_trail_decay_fast         0.15
cursor_trail_decay_slow         0.45
cursor_trail_start_threshold    2

# -- Terminal bell -- #
enable_audio_bell               no
window_alert_on_bell            yes

# -- Shell e Integración -- #
shell                           fish
shell_integration               enabled
confirm_os_window_close         0

# -- Window Layout -- #
remember_window_size            no
initial_window_width            120c
initial_window_height           35c
window_padding_width            15
hide_window_decorations         yes
placement_strategy              center

# -- Background -- #
background_opacity              0.80
dynamic_background_opacity      yes
scrollbar_handle_opacity        0
scrollbar_track_opacity         0

# -- URLs -- #
url_style                       curly
url_prefixes                    http https file ftp
detect_urls                     yes
open_url_modifiers              kitty_mod

# -- Clipboard -- #
clipboard_control               write-clipboard read-clipboard
copy_on_select                  yes

# -- Layouts -- #
enabled_layouts                 tall,stack,fat,grid

# -- Performance -- #
sync_to_monitor                 yes
repaint_delay                   8
input_delay                     3

# BEGIN_KITTY_FONTS
font_family                     family="Adwaita Mono"
bold_font                       auto
italic_font                     auto
bold_italic_font                auto
