####################
## -- Hypridle -- ##
####################

listener {
    timeout = 120
    on-timeout = hyprlock
    ignore_inhibit = true
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
    ignore_inhibit = true
}